In [78]:
import numpy as np

def print_matrix(matrix):
    for line in matrix:
        print(line)

# Contruindo a Malha
h = 0.1

x = np.arange(0,1+h, h)
y = np.arange(-1,1+h, h)


print(x)
print(y)

n = len(x)
m = len(y)

print(n)
print(m)




[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
[-1.00000000e+00 -9.00000000e-01 -8.00000000e-01 -7.00000000e-01
 -6.00000000e-01 -5.00000000e-01 -4.00000000e-01 -3.00000000e-01
 -2.00000000e-01 -1.00000000e-01 -2.22044605e-16  1.00000000e-01
  2.00000000e-01  3.00000000e-01  4.00000000e-01  5.00000000e-01
  6.00000000e-01  7.00000000e-01  8.00000000e-01  9.00000000e-01
  1.00000000e+00]
11
21


In [79]:
# Construindo o Sistema.


u = np.zeros((len(y), len(x)))


c = 4 * np.pi **2 -3

#print_matrix(mesh)

u[:, 0] = 0
u[:, -1] = 0

print("--------------------------------")
print_matrix(u)

# AU = F

mesh = []
for iy in reversed(y):
    line = []
    for ix in x:
        line.append((ix, iy))
    mesh.append(line)

for row in mesh:
    for x, y in row:
        print(f"({x:.1f}, {y:.1f})", end="  ")  # Added extra space to make it square
    print()

--------------------------------
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
(0.0, 1.0)  (0.1, 1.0)  (0.2, 1.0)  (0.3, 1.0)  (0.4, 1.0)  (0.5, 1.0)  (0.6, 1.0)  (0.7, 1.0)  (0.8, 1.0)  (0.9, 1.0)  (1.0, 1.0)  
(0.0, 0.9)  (0.1, 0.9)  (0.2, 0.9)  (0.3, 0.9)  (0.4, 0.9)  (0.5, 0.9)  (0.6, 0.9)  (0.7, 0.9)  (0.

In [80]:
# Para i = 0 j = 0 (0,1) -> (1,1)

for el in u[0]:
    d


0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
